# Generated by Django 4.2.4 on 2023-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_last_modified',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена'),
        ),
    ]
